# Generated by Django 2.0.3 on 2018-08-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleorBanner',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('banner_text', models.CharField(max_length=255)),
                ('_text_color', models.CharField(default='#f2ece7', max_length=7)),
                ('_banner_color', models.CharField(
                    default='#ff473c', max_length=7)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('view', 'Can view banners'), ('edit', 'Can edit banners')),
            },
        ),
    ]
